language: php
php:
  - '5.6'
  - '7.0'
install:
  - composer install --no-interaction --prefer-source
before_script:
  - sudo apt-get update
  - sudo apt-get install -y build-essential software-properties-common
  - sudo apt-get install -y libsqlite3-dev ruby1.9.1-dev
  - sudo gem install mime-types --version "< 3"
  - sudo gem install --conservative mailcatcher
  - sudo mailcatcher --foreground --http-ip=0.0.0.0
script: vendor/bin/phpunit