language: php
php:
  - '7.0'
before_install:
  - rvm install 1.9.2
install:
  - composer install --no-interaction --prefer-source
before_script:
  - which -a ruby
  - gem install mime-types --version "< 3"
  - gem install --conservative mailcatcher
  - mailcatcher --foreground --http-ip=0.0.0.0
script: vendor/bin/phpunit