{
  "language": "php",
  "php": "7.2",
  "before_install": [
    "rvm install 1.9.3"
  ],
  "install": [
    "composer install --no-interaction --prefer-source"
  ],
  "before_script": [
    "gem install mime-types --version \"< 3\"",
    "gem install --conservative mailcatcher",
    "mailcatcher --http-ip=0.0.0.0"
  ],
  "script": "vendor/bin/phpunit",
  "group": "stable",
  "dist": "precise",
  "os": "linux"
}
