language: php
php:
  - '5.6'
  - '7.0'
install:
  - composer install --no-interaction --prefer-source
before_script:
  - sudo apt-get update
  - sudo apt-get install -y libsqlite3-dev ruby
  - sudo apt-get install rubygems
  - sudo gem install mime-types -v 2.6.2
  - sudo gem install mailcatcher
  - sudo mailcatcher --foreground --http-ip=0.0.0.0
  - export MAIL_PORT=1025
  - export MAIL_HOST=localhost
script: vendor/bin/phpunit